### ISSUE TITLE
PSR3 Journal

### ISSUE THREAD

**Issue by nikkobautista** [daylerees/scientist#2]
https://packagist.org/packages/nx/scientist-psr3-journal

**Comment by daylerees** [comment]
Damn Nikko, that was quick! Thanks so much. :)

I'll leave the issue open for tomorrow (3am currently) and then I'll add it to the docs.

**Comment by daylerees** [comment]
Added to the readme, and soon to be added to the docs. Credit granted. Thanks very much for your contribution! :)

**Comment by nikkobautista** [comment]
Thanks Dayle!
