### ISSUE TITLE
Silex Wrapper

### ISSUE THREAD

**Issue by mauro-moreno** [daylerees/scientist#3]
[https://packagist.org/packages/mauro-moreno/silex-scientist](https://packagist.org/packages/mauro-moreno/silex-scientist)

**Comment by daylerees** [comment]
Awesome! Thank you very much. :) Will add to the docs tomorrow.

**Comment by daylerees** [comment]
Added to the readme, and soon to be added to the docs. Credit granted. Thanks very much for your contribution! :)
