### ISSUE TITLE
Closure based matchers 

### ISSUE THREAD

**Issue by devmsh** [daylerees/scientist#30]
Must of the time, the matcher class will consist only of single-function `match`, so why we can't allow closure based matchers like

```php
$experiment->matcher(function ($control, $trial) {
    return $control == $trial;
});
```

**Comment by willrowe** [comment]
This has already been made possible by #17.

**Comment by devmsh** [comment]
But it's not tagged in the latest release?

**Comment by willrowe** [comment]
It's been there since v2.0.0.

**Comment by devmsh** [comment]
Thanks @willrowe , I just notice the `ClosureMatcher` class in the PR.  why can't we just use the closure directly like my example above? 

If there is a technical challenge or a design decision than prevent that I can close the issue, otherwise I can open PR for this.

**Comment by willrowe** [comment]
The `matcher` method expects an instance of `Matcher`, so introducing a class that accepts a closure was the approach that required the least amount of changes in order to add support.
