### ISSUE TITLE
Documentation links are dead

### ISSUE THREAD

**Issue by RyanMoultrup** [daylerees/scientist#31]
The link for a more detailed description of the project and the link for the full documentation are dead and both lead to a blank page.

**Comment by arcticlinux** [comment]
It's available at the internet archive, but I don't think there is an easy way to restore it from the snapshot.

https://web.archive.org/web/20210122194149/https://scientist.readme.io/

**Comment by arcticlinux** [comment]
I copied the bulk of the documentation from archive.org into the [wiki](https://github.com/daylerees/scientist/wiki).

@daylerees  if you could update the project link to point to it, or remove the link, either works for me.

**Comment by daylerees** [comment]
Updated the URL, thanks both. Good thinking on using the archive! :)
