### ISSUE TITLE
Provide a grab-and-run example

### ISSUE THREAD

**Issue by IngwiePhoenix** [daylerees/scientist#9]
I read over the website and the local README, but I was missing a "just copy and try" example. Piecing the example together from the docs does work, but for just wanting to test the code, it isn't the most convenient ;).

Having a thing that a user can just copy to a local file, and run, will likely result in the user making a faster decision if they'd like to use this project, or not.

Then again, this might also just be a personal opinion...

**Comment by daylerees** [comment]
Yep, I know what you mean. It's a rather tricky one. Padding out the example with actual callbacks makes it much longer, I'm worried that might also be offputting. I'll try to think of something.

**Comment by danhanly** [comment]
Perhaps a 'Simple Example' then a separate 'Complex Example' to really
drive the point home.
